function gluing = create_gluing_nonseparating_S2()
%CREATE_GLUING_NONSEPARATING_S2  Build the gluing struct for the non-separating
% genus-2 surface constructed from 4 right-angled hexagons.
%
% Unlike the standard_S2 gluing (which has 3 separating curves), this gluing
% connects ALL twisted sides across the {hex 1,2} <-> {hex 3,4} boundary,
% yielding a single non-separating curve.
%
% Returns a struct with fields:
%   .name               - identifier string
%   .pairings           - 4x6 cell array of pairing descriptors
%   .noncoherent_pairs  - Nx2 matrix of (from_hex, to_hex) pairs requiring
%                         orientation reversal
%   .curve_combinations - 1x3 cell array; each entry is an Mx2 matrix of
%                         [hex, side] pairs marking curve crossings

gluing.name = 'nonseparating_S2';

% --- Visualization style -------------------------------------------------
gluing.hex_style = @get_hexagon_style_nonseparating;

% --- Hexagon shape data --------------------------------------------------
% All 4 hexagons are identical: built via
% rectangular_hexagon_centered(L(1)/2, L(2)/2, L(3)/2).
gluing.hex_curve_indices = [1,2,3; 1,2,3; 1,2,3; 1,2,3];

% --- Orientation-reversing pairs ----------------------------------------
gluing.noncoherent_pairs = [1,2; 1,3; 2,1; 2,4; 3,1; 3,4; 4,2; 4,3];

% --- Curve crossing data -------------------------------------------------
% Each curve corresponds to one odd side across all 4 hexagons.
gluing.curve_combinations = {
    [1,1; 2,1; 3,1; 4,1], ...   % curve 1 — side 1 of all hexes
    [1,3; 2,3; 3,3; 4,3], ...   % curve 2 — side 3 of all hexes
    [1,5; 2,5; 3,5; 4,5]  ...   % curve 3 — side 5 of all hexes
};

% --- Pairing table -------------------------------------------------------
% gluing.pairings{i,s}: descriptor for geodesic exiting hex i through side s.
%
% Simple pairing fields:
%   .type = 'simple'
%   .tgt_hex, .tgt_side
%   .src_vtx  = [v1, v2]   (vertex indices in the source hex)
%   .tgt_vtx  = [w1, w2]   (vertex indices in the target hex)
%
% Twisted pairing fields:
%   .type = 'twisted'
%   .primary_tgt_hex, .primary_tgt_side    (when overshoot == 0 or 2)
%   .secondary_tgt_hex, .secondary_tgt_side (when overshoot == 1)
%   .src_vtx       = [v1, v2]
%   .primary_vtx   = [w1, w2]   (in primary_tgt_hex)
%   .secondary_vtx = [x1, x2]  (in secondary_tgt_hex)
%   .twist_param_index = 1|2|3
%   .twist_sign = +1 (use t) or -1 (use 2*pi - t)

gluing.pairings = cell(4, 6);

% ---- Simple pairings (sides 2, 4, 6) ------------------------------------

gluing.pairings{1,2} = struct('type','simple','tgt_hex',2,'tgt_side',2, ...
    'src_vtx',[2,3],'tgt_vtx',[2,3]);
gluing.pairings{1,4} = struct('type','simple','tgt_hex',2,'tgt_side',4, ...
    'src_vtx',[4,5],'tgt_vtx',[4,5]);
gluing.pairings{1,6} = struct('type','simple','tgt_hex',2,'tgt_side',6, ...
    'src_vtx',[6,1],'tgt_vtx',[6,1]);

gluing.pairings{2,2} = struct('type','simple','tgt_hex',1,'tgt_side',2, ...
    'src_vtx',[2,3],'tgt_vtx',[2,3]);
gluing.pairings{2,4} = struct('type','simple','tgt_hex',1,'tgt_side',4, ...
    'src_vtx',[4,5],'tgt_vtx',[4,5]);
gluing.pairings{2,6} = struct('type','simple','tgt_hex',1,'tgt_side',6, ...
    'src_vtx',[6,1],'tgt_vtx',[6,1]);

gluing.pairings{3,2} = struct('type','simple','tgt_hex',4,'tgt_side',2, ...
    'src_vtx',[2,3],'tgt_vtx',[2,3]);
gluing.pairings{3,4} = struct('type','simple','tgt_hex',4,'tgt_side',4, ...
    'src_vtx',[4,5],'tgt_vtx',[4,5]);
gluing.pairings{3,6} = struct('type','simple','tgt_hex',4,'tgt_side',6, ...
    'src_vtx',[6,1],'tgt_vtx',[6,1]);

gluing.pairings{4,2} = struct('type','simple','tgt_hex',3,'tgt_side',2, ...
    'src_vtx',[2,3],'tgt_vtx',[2,3]);
gluing.pairings{4,4} = struct('type','simple','tgt_hex',3,'tgt_side',4, ...
    'src_vtx',[4,5],'tgt_vtx',[4,5]);
gluing.pairings{4,6} = struct('type','simple','tgt_hex',3,'tgt_side',6, ...
    'src_vtx',[6,1],'tgt_vtx',[6,1]);

% ---- Twisted pairings (sides 1, 3, 5) -----------------------------------
% All twisted sides pair between the {1,2} and {3,4} hex groups.
% primary_tgt_side = secondary_tgt_side = source side (same side number).

% Hex 1
gluing.pairings{1,1} = struct('type','twisted', ...
    'primary_tgt_hex',3,'primary_tgt_side',1, ...
    'secondary_tgt_hex',4,'secondary_tgt_side',1, ...
    'src_vtx',[1,2],'primary_vtx',[1,2],'secondary_vtx',[2,1], ...
    'twist_param_index',1,'twist_sign',+1);

gluing.pairings{1,3} = struct('type','twisted', ...
    'primary_tgt_hex',3,'primary_tgt_side',3, ...
    'secondary_tgt_hex',4,'secondary_tgt_side',3, ...
    'src_vtx',[3,4],'primary_vtx',[3,4],'secondary_vtx',[4,3], ...
    'twist_param_index',2,'twist_sign',+1);

gluing.pairings{1,5} = struct('type','twisted', ...
    'primary_tgt_hex',3,'primary_tgt_side',5, ...
    'secondary_tgt_hex',4,'secondary_tgt_side',5, ...
    'src_vtx',[5,6],'primary_vtx',[5,6],'secondary_vtx',[6,5], ...
    'twist_param_index',3,'twist_sign',+1);

% Hex 2
gluing.pairings{2,1} = struct('type','twisted', ...
    'primary_tgt_hex',4,'primary_tgt_side',1, ...
    'secondary_tgt_hex',3,'secondary_tgt_side',1, ...
    'src_vtx',[1,2],'primary_vtx',[1,2],'secondary_vtx',[2,1], ...
    'twist_param_index',1,'twist_sign',-1);

gluing.pairings{2,3} = struct('type','twisted', ...
    'primary_tgt_hex',4,'primary_tgt_side',3, ...
    'secondary_tgt_hex',3,'secondary_tgt_side',3, ...
    'src_vtx',[3,4],'primary_vtx',[3,4],'secondary_vtx',[4,3], ...
    'twist_param_index',2,'twist_sign',-1);

gluing.pairings{2,5} = struct('type','twisted', ...
    'primary_tgt_hex',4,'primary_tgt_side',5, ...
    'secondary_tgt_hex',3,'secondary_tgt_side',5, ...
    'src_vtx',[5,6],'primary_vtx',[5,6],'secondary_vtx',[6,5], ...
    'twist_param_index',3,'twist_sign',-1);

% Hex 3
gluing.pairings{3,1} = struct('type','twisted', ...
    'primary_tgt_hex',1,'primary_tgt_side',1, ...
    'secondary_tgt_hex',2,'secondary_tgt_side',1, ...
    'src_vtx',[1,2],'primary_vtx',[1,2],'secondary_vtx',[2,1], ...
    'twist_param_index',1,'twist_sign',-1);

gluing.pairings{3,3} = struct('type','twisted', ...
    'primary_tgt_hex',1,'primary_tgt_side',3, ...
    'secondary_tgt_hex',2,'secondary_tgt_side',3, ...
    'src_vtx',[3,4],'primary_vtx',[3,4],'secondary_vtx',[4,3], ...
    'twist_param_index',2,'twist_sign',-1);

gluing.pairings{3,5} = struct('type','twisted', ...
    'primary_tgt_hex',1,'primary_tgt_side',5, ...
    'secondary_tgt_hex',2,'secondary_tgt_side',5, ...
    'src_vtx',[5,6],'primary_vtx',[5,6],'secondary_vtx',[6,5], ...
    'twist_param_index',3,'twist_sign',-1);

% Hex 4
gluing.pairings{4,1} = struct('type','twisted', ...
    'primary_tgt_hex',2,'primary_tgt_side',1, ...
    'secondary_tgt_hex',1,'secondary_tgt_side',1, ...
    'src_vtx',[1,2],'primary_vtx',[1,2],'secondary_vtx',[2,1], ...
    'twist_param_index',1,'twist_sign',+1);

gluing.pairings{4,3} = struct('type','twisted', ...
    'primary_tgt_hex',2,'primary_tgt_side',3, ...
    'secondary_tgt_hex',1,'secondary_tgt_side',3, ...
    'src_vtx',[3,4],'primary_vtx',[3,4],'secondary_vtx',[4,3], ...
    'twist_param_index',2,'twist_sign',+1);

gluing.pairings{4,5} = struct('type','twisted', ...
    'primary_tgt_hex',2,'primary_tgt_side',5, ...
    'secondary_tgt_hex',1,'secondary_tgt_side',5, ...
    'src_vtx',[5,6],'primary_vtx',[5,6],'secondary_vtx',[6,5], ...
    'twist_param_index',3,'twist_sign',+1);

end
